language: java

jdk:
- oraclejdk8

sudo: false

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
#  on:
#    tags: true

#install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: "mvn cobertura:cobertura"
#script: mvn test -P !build-extras -B
cache:
  directories:
    - ~/.m2/repository

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - ./cd/before-deploy.sh
#  - ./cd/deploy.sh

#env:
#  global:
#    - secure: "fmbMY818uooFcdvPrknkOw9twdwmSmZmQ1wrEM5UNQGaQDLcn9KU17GaQ9ARC6XWZRwarhhEDWamcTFa8G8dQrF8FeiXmjQq5ry9/Gp479SZJw3qly5FY8eEoATEOEjLXiM5vSenSqoawKDboDKevWYTcsRsfVIDcCBtRl4kqYYzBfBQW+wRwwkSkywm8t2LFh7SQOZk15t2IwCw7HEU+faBuwY7mFm1D8d8tm7KnrBJqRR57YpMdDk41/WhuYKsAZqZpkGBj2G3Kq8PoqmqdyUdFOzwzlNPLAULavBkZT2p10DNLtlESZ0Js1AsNwm8RsJnT8UoVxVv+5iaAkXc2syke9FxtQgORGn0QrRFQ//svkfMXFop0oX9IkAt2AZ8NRWEMkOSdpWeENsxbAbYJEUlniZqBCO5LAu26C1AJQyKHc+cPTGOEsnLZicwCiekYqyvtxrRh8vxbgXoa5Ipp+YszQs5Khg2FMaDOVJ+joL3khUGfL09X97VMBnAGYOzVQRAojMTEaPKD/JWGQsWB1suLCkMBf19drmuuJAjFCO0Ct4/b+83kLDBSY4Kxa147yQFfvTF5U+xZkZtv1ejXZNIevWtph6oCkgoQm+8TkJN1FiNGnneMVETpoRU6lfpPHETXyCGae8BpLBP5Ag3S3HLlzIWBTnAJwfUHQhmWKw="
#    - # ^^ OSSRH_JIRA_USERNAME
#    - secure: "J+5jd20VqjCl/8FgpgWT8r9xcOzRDXJFC9VnfpXRTMjKeJ4ck8wXigdWK/4bpB7/nLj8PgD8bXxYXBgt2IczbOnvHVPjzkTON1s4ytDLnQOL/QHeAP+9Ym8XD0ZhjZFVMOkgEV9wXpn8D3TDp7u2OM3eY+DmX6sOzVGHFC5D4W3Axr58gpnOvDgSGugzQeogv0c6tka4WMAoEBH5c/D7WQ9jPbnHhUP+tKj7vp7HYZAW+HTWloUKLSjv9DQ5CGoq8LYeXB49F9hyxTduyreZESPpLJESVvxkCKdhI+cSNBDwtyWucQ3t5gPQzp4HBH/7kLmX1jERtmJLTnB1RUrU3kNUFFeK+SLsVBP7WwVCT9f4yeNSlPAAr22bAgVnE5SiI34LDtirjjDtSIJeE8+5D4SPmWwSozKYT4zUvcBYlFF1sARUgRC5bbazzp5KC7Da2P5Xb7BEh7eOtf5Grs7hVLtZlCric6GmP3nBXKU55ecUbIs6kNBpAGITKeg1OxB5yXeLVXx4+SWRGOgfvs205D2/86heC0dqyiM5tQe5J4zK30Kp64S1aD2ejj/eS/ctTGoVoqf6/K5xtxi1ZlVZ60hxfMp0hqfJqRAIetv9F401yVbZrfdOhFijxs2eovSYBVo5+GynBq9t1wHyqzu5QKhRZi+kPMksMzWm+yMbw24="
#    - # ^^ OSSRH_JIRA_PASSWORD
#    - secure: "Q4trd3z+zrWvihbhsOa6n4Cdpka3Q9Ad9CsaJnLM9RgWuHzDYDo1KPvXmESIniy3vzpmFxXbVSscRli5A/g27KphD6qpiF1Fhsr2IhiE3RIVVc+zRsJgZ+VB9s1z1whceH3pTVJFWQNX2B0BAF+WjaglDTstPQBlbmJJ14UvCTwS1xIjHEUjorFe9+m89cW3qek/s9Zb2hbM9YOZkeflBLRu8zhh5PuBGd6FbcErYrNu5t3QAHTZ6wOIPAPNqvbX+lgH/68Xxoq4EjThLXLSU0jGYziwzrWT1drjMCuJd5FwfkFnDJdP4DC2cA+PelJ5WLpxoyFkZOpOl8K0zwUZ9NT84n03IOv7wFITYnfUM4sg57x6XXzhgJ7qlM0E9lzsuDnAbb3DEZGBjTWRqqkWxlcL4+7EgGGvhBqR0877vbneSun2yiIAaEz6loz5q08/1Rs2Q3jLOjQccdp0Y5pOKOnp6beUg7jyN+3CNVv5ImnsM0oFm0b+PD885HukVzO3S/4EGn+KCOBvDGyKGmeaOZmIPhSMIKUNVXa19YFi/mInqsx6O220aK95XkWu5G+Ny8U6O9SqTH/vloFfFrveKdEk59flMNjCt1meeEQdnieTb0aNTxFA7/Qn19Jz0SXYYOsafnDcmKpDPTvHEPuw+hsQBJj2alkfTSvfEMCZSmk="
#    - # ^^ GPG_KEY_NAME
#    - secure: "RgSf5XMTBtnLi2DF9RftApUutE7FSbGLqWvCp4JtcBOnGPS0fiZyCq0a2SjIjrNElBVX+cy0wLhNWcIKQZiIIB/Ubpv5WWGVTSK1qGpEE6GSQHDzUCwSB8HWhJFLLfLdxhzlJ4M9BSa8fiQtdE4jWpQ3WlDombnc7v45FaaDG5w8MtOa5nI9iVg1XHbK6pu7EeWKQF1uh5/C2kPTtl9n61HpY1GE6tPtev7ZT2k60gKP64nkAOyCLgdNRl9YMr2EAW7pDHohiHgXoNAb0NFxVNA7TatxhpR8CvoX3bOaKcmM8khq13dfXEIHiQ1FLccwol+kEvYfhXWP/ycyeCAkHfmxFnQWC/ewDqN96dUseS1wPruo1kQXiQha71sp0VSUEjT3TJSLWnY9zNuIXjP/huKLgx/TKp4zhK6/Zf6bRHlgMzp3hJ+szF5w2K/oVyoHnxxIgvM32n6kNAVDZ2vDnH8xkRfFasjOZyCpmGDqOBePC5mLnrSLQ5cRDA1vqvZk6qJnpHq9hfTK1AYP+9Aki4i8pKOrFP3VN750gTjPh2HrQPZLAwdhiC4nAiv1Apluyw0Vr7fHEMlhq06Omuyis5kubk8Ec/rGWCwi4AXLYqilvJgpgeGRYjvLzsbvArhqJQX7dAASdUntIMfo8Jhms35rLg5b3CP/Bp8iW+tu+lU="
#    - # ^^ GPG_PASSPHRASE