language: java

jdk:
- oraclejdk8

sudo: false

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)