language: java
jdk:
- oraclejdk8
sudo: false
stages:
  - test
  - name: deploy
  - codecov
jobs:
  include:
    - stage: test
      script: mvn test
    - stage:
      script:
        - mvn cobertura:cobertura
        - bash <(curl -s https://codecov.io/bash)
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
#script: mvn cobertura:cobertura
cache:
  directories:
  - "~/.m2/repository"
deploy:
  provider: releases
  api_key:
    secure: I2EqX712tNCalpvG/RRbAJuJgka18CMpJRFupXrSPKNgNQb4O25T/cuvbqGzo4seOFnrl9ms1NIE7pgKUgXjfTjqnbji1XvlwcYooAIItPKxpEbVaCvW6kYxg7LJCplatvQ0GrYQIWUTpSRRZl0GQbTf4degYtJHUudyzNCyO7hD7Kc84W2+rtXLBK7pTUjeXRP7/WX77DufM6xpK3K9SSqpe2Gfocigy7CuWPxU1haH4viYauSUrbEcJD318jXEsLDII9maaQ+vU/lwS7z98RWhyxuu/PmC7HT+iKszMeu1y2UiR2xrP63jZBFNlBoETWoSrGstchjzoOw1u+PwLtpvz6h5HgpFX+1mJr/+sVMl4HHk6MSIbeSgGX/qAHWZS7298UqzfTKnnFzBrerqE1MICdNhrkSrfPOwzIZ54Gd8399vMCh2mgVi2Rc1nh2IWqoMzDqgWLwcu00yVCAGcM38WACWQyjxgBCM4eSD6zVDXsQ/wLuELXytbsojvY79EYCISeWel24UpJ62I1noLa+bmw3LiSUeDKXU9XOjEYoOuLjexkRnERVfNo8kb3EYsyQTr+T2n6Db/uYLBgNTL/qvBVPTiXs8uwmmayH+QNrI3RaRHVhTsmrEZlwmWGjO5hKWlAuTGqi+Zu4wOsx7/3BndpL5pJ3DXnRED1kXS3U=
  file:
    - fastball/target/fastball-$project_version.jar
  skip_cleanup: true
  on:
    repo: l0n9h02n/fastball
  name: $project_version
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central
script:
#    - mvn cobertura:cobertura
    - mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
#after_success:
#- bash <(curl -s https://codecov.io/bash)